version: '3.7'

services:
  firefly_iii:
    build:
      context: docker/
      dockerfile: Dockerfile.amd64
      args:
        version: 5.4.0-alpha.2
    volumes:
      - firefly_iii_export_TEMPORARY:/var/www/firefly-iii/storage/export
      - firefly_iii_upload_TEMPORARY:/var/www/firefly-iii/storage/upload
    env_file:
      - .env
    depends_on:
      - firefly_iii_db
    restart: unless-stopped
    ports:
      - "8080:8080"

  firefly_iii_db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=firefly
      - POSTGRES_PASSWORD=secret_firefly_password
    volumes:
      - firefly_iii_db_TEMPORARY:/var/lib/postgresql/data

volumes:
   firefly_iii_export_TEMPORARY:
   firefly_iii_upload_TEMPORARY:
   firefly_iii_db_TEMPORARY:

